FROM node:24.16.0-alpine3.22 AS builder

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

WORKDIR /app

COPY --chown=nextjs:nodejs  package.json package-lock.json ./

RUN npm ci

COPY --chown=nextjs:nodejs . .

COPY --chown=nextjs:nodejs ./docker/migrate-script.sh .
RUN chmod +x migrate-script.sh

USER nextjs

CMD ["./migrate-script.sh"]