FROM node:24.16.0-alpine3.22 AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

COPY ./docker/start-script.sh .
RUN chmod +x start-script.sh

RUN npm run build

FROM node:24.16.0-alpine3.22

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

WORKDIR /app

RUN apk add --no-cache postgresql-client

COPY --chown=nextjs:nodejs --from=builder /app/package.json ./package.json
COPY --chown=nextjs:nodejs --from=builder /app/next.config.ts ./next.config.ts
COPY --chown=nextjs:nodejs --from=builder /app/drizzle.config.ts ./drizzle.config.ts
COPY --chown=nextjs:nodejs --from=builder /app/public/ ./public
COPY --chown=nextjs:nodejs --from=builder /app/.next/ ./.next/
COPY --chown=nextjs:nodejs --from=builder /app/src/lib/db/ ./src/lib/db/
COPY --chown=nextjs:nodejs --from=builder /app/node_modules/ ./node_modules/
COPY --chown=nextjs:nodejs --from=builder /app/tsconfig.json ./tsconfig.json
COPY --chown=nextjs:nodejs --from=builder /app/start-script.sh .

USER nextjs

EXPOSE 3000

CMD ["./start-script.sh"]