FROM node:24.16.0-alpine3.22 AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY ./docker/start-script.sh .
RUN chmod +x start-script.sh

COPY . .

RUN npm run build

FROM node:24.16.0-alpine3.22

WORKDIR /app

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

RUN apk add --no-cache libc6-compat

COPY --from=builder /app/public/ ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/next.config.ts ./next.config.ts
COPY --from=builder /app/drizzle.config.ts ./drizzle.config.ts
COPY --from=builder /app/src/lib/db/ ./src/lib/db/
COPY --from=builder /app/tsconfig.json ./tsconfig.json
COPY --from=builder /app/start-script.sh .

RUN npm install drizzle-kit tsx 

RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

CMD ["./start-script.sh"]