FROM node:24.16.0-alpine3.22 AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

COPY ./docker/start-script.sh .
RUN chmod +x start-script.sh

RUN npm run build

FROM node:24.16.0-alpine3.22

WORKDIR /app

RUN apk add --no-cache postgresql-client

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.ts ./next.config.ts
COPY --from=builder /app/drizzle.config.ts ./drizzle.config.ts
COPY --from=builder /app/public/ ./public
COPY --from=builder /app/.next/ ./.next/
COPY --from=builder /app/src/lib/db/ ./src/lib/db/
COPY --from=builder /app/node_modules/ ./node_modules/
COPY --from=builder /app/tsconfig.json ./tsconfig.json
COPY --from=builder /app/start-script.sh .

EXPOSE 3000

CMD ["./start-script.sh"]